#pragma once
#include"Person.h"
#include"LMSDB.h"
#include"AcademicOfficer.h"
#include"Attendance.h"
#include"Course.h"
#include"Evaluation.h"
#include"EvaluationResult.h"
#include"Faculty.h"
#include"Registration.h"
#include"Section.h"
#include"Session.h"
#include"Student.h"
