# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = GUI
DESTDIR = ../Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./LMS.h \
    ./GUI.h \
    StudentLogin.h
SOURCES += ./GUI.cpp \
    ./main.cpp \
    StudentLogin.cpp
FORMS += ./GUI.ui \
    StudentLogin.ui
RESOURCES += GUI.qrc
